### ISSUE TITLE
In any class first we create constructor then we use it's body  in other function . In User class look like first you create all the functions and then write constructor. Write Constructor over the all functions. 

### ISSUE THREAD

**Issue by prithviraj86** [13014932/Satpal-Codec#1]
https://github.com/13014932/Satpal-Codec/blob/75e8f89457c9d4da12410b35fb6b432c27563b1b/Dependency%20Injection.php#L37

**Comment by 13014932** [comment]
Sir, I update the issue by defining the class User __construct after the variable declaration.
